name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "0adc2ce4-38cd-4791-be49-9a6c5b693e66"

[[kv_namespaces]]
binding = "kv"
id = "6f6864dc59884ea78d74ac4aab19c4cb"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

#[[send_email]]
#name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
domain = ["grok.smchat.cn"]
admin = "admin@grok.smchat.cn"
jwt_secret = "chow147258369"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
